### ISSUE TITLE
[BUG] 앱 초기 실행 시 권한 허용 후 카메라스크린에서 권한 확인 못 하는 이슈

### ISSUE THREAD

**Issue by ethan-oh** [TheJoeunDorothy/Dorothy#8]
**버그 설명**

**어떻게 해서 버그 발견했는지**
cameraVM이 두 번 put되는 것을 확인.
이전 이슈를 컨트롤러 onInit 이 아닌 위젯 빌드 시 권한 가져오게 임시로 fix했지만 이상적인 해결책이 아님.

**어떻게 고쳤으면 좋겠는지**
put을 한 번만 되게 수정하여 oninit 시에 권한 한 번만 가져올 수 있게끔 수정 요망

**디버그 내용**
없음.

**Additional context**

**Comment by kangdeagyu** [comment]
get.find로 변경 버그 수정
